# Generated by Django 3.2.6 on 2021-08-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="version",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
