# Generated by Django 3.2.6 on 2021-08-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0003_rename_custom_env_vars_service_custom_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="custom_config",
            field=models.JSONField(blank=True),
        ),
    ]
