# Generated by Django 3.2.6 on 2021-08-19 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0004_alter_service_custom_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="version",
        ),
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
