# Generated by Django 3.2.6 on 2021-08-20 06:33

from django.db import migrations

import dockercontroller.apps.controller.models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0006_auto_20210819_1730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=dockercontroller.apps.controller.models.CustomDateTimeField(
                auto_now=True
            ),
        ),
    ]
